// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"recipe_service/internal/api"
	"recipe_service/internal/api/handler"
	"recipe_service/internal/config"
	"recipe_service/internal/db"
	"recipe_service/internal/repository"
	"recipe_service/internal/service"
)

// Injectors from wire.go:

func Initialize(cfg config.Config) (*http.Server, error) {
	sqlxDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	err = db.Migrate(sqlxDB)
	recipeRepository := repository.NewRecipeRepository(sqlxDB)
	recipeService := service.NewRecipeService(recipeRepository)
	recipeHandler := handler.NewRecipeHandler(recipeService)
	server := http.NewServer(recipeHandler)
	return server, nil
}
