// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"user_service/internal/api"
	"user_service/internal/api/handler"
	"user_service/internal/config"
	"user_service/internal/db"
	"user_service/internal/repository"
	"user_service/internal/service"
)

// Injectors from wire.go:

func Initialize(cfg config.Config) (*http.Server, error) {
	sqlxDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	err = db.Migrate(sqlxDB)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(sqlxDB)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	server := http.NewServer(userHandler)
	return server, nil
}
